version: "2"

networks:
  gregor-chair-network-r2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
#        - gateway: 172.16.240.11

services:
  robot2coordinator:
    build:
      context: ./Robot2_Coordinator
      dockerfile: Dockerfile
    container_name: r2coordinator
    networks:
      gregor-chair-network-r2:
        ipv4_address: 192.168.2.20
    volumes:
      - /tmp:/tmp
    links:
      - workertask2
      - workertask3
      - workertask5
    cpus: 0.7
    mem_limit: 500m
  workertask2:
    build:
      context: ./WorkerTask2
      dockerfile: Dockerfile
    container_name: workertask2
    volumes:
      - /tmp:/tmp
    links:
      - robot2controller
    environment:
      - PYTHONUNBUFFERED=1
    cpus: 0.7
    mem_limit: 500m
  workertask3:
    build:
      context: ./WorkerTask3
      dockerfile: Dockerfile
    container_name: workertask3
    volumes:
      - /tmp:/tmp
    links:
      - robot2controller
    environment:
      - PYTHONUNBUFFERED=1
  workertask5:
    build:
      context: ./WorkerTask5
      dockerfile: Dockerfile
    container_name: workertask5
    volumes:
      - /tmp:/tmp
    links:
      - robot2controller
    environment:
      - PYTHONUNBUFFERED=1
    cpus: 0.7
    mem_limit: 500m
  robot2controller:
    build:
      context: ./RobotControllerMs
      dockerfile: Dockerfile
    container_name: robot2controller
    volumes:
      - /tmp:/tmp
      - /dev/gpiomem:/dev/gpiomem
    privileged: true
    environment:
      - PYTHONUNBUFFERED=1
    cpus: 0.7
    mem_limit: 500m

