version: "2"

networks:
  gregor-chair-network-r2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
#        - gateway: 172.16.240.11

services:
  node-exporter:
    image: prom/node-exporter:v0.18.1
    container_name: r2_node-exporter
    ports:
      - "9100:9100"
    restart: always
  cadvisor:
    image: budry/cadvisor-arm:latest #google/cadvisor:v0.33.0  #
    container_name: r2_cadvisor
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true
    depends_on:
      - robot2coordinator
  r2_assembly_coordinator:
    build:
      context: ./Robot2_Coordinator
      dockerfile: Dockerfile
    container_name: r2_assembly_coordinator
    networks:
      gregor-chair-network-r2:
        ipv4_address: 192.168.2.20
    volumes:
      - /tmp:/tmp
    links:
      - workertask2
      - workertask3
      - workertask5
    mem_limit: 500m
  workertask2:
    build:
      context: ./WorkerTask2
      dockerfile: Dockerfile
    container_name: workertask2
    volumes:
      - /tmp:/tmp
    links:
      - robot2controller
    environment:
      - PYTHONUNBUFFERED=1
    mem_limit: 500m
  workertask3:
    build:
      context: ./WorkerTask3
      dockerfile: Dockerfile
    container_name: workertask3
    volumes:
      - /tmp:/tmp
    links:
      - robot2controller
    environment:
      - PYTHONUNBUFFERED=1
    mem_limit: 500m
  workertask5:
    build:
      context: ./WorkerTask5
      dockerfile: Dockerfile
    container_name: workertask5
    volumes:
      - /tmp:/tmp
    links:
      - robot2controller
    environment:
      - PYTHONUNBUFFERED=1
    mem_limit: 500m
  r2_controller:
    build:
      context: ./RobotControllerMs
      dockerfile: Dockerfile
    container_name: robot2controller
    volumes:
      - /tmp:/tmp
      - /dev/gpiomem:/dev/gpiomem
    privileged: true
    environment:
      - PYTHONUNBUFFERED=1
    mem_limit: 500m

