version: "3"

networks:
  gregor-chair-network:
    external: true
#    driver: overlay
#    ipam:
#      driver: default
#      config:
#        - subnet: 192.1.1.0/24


services:
### W1 SERVICES ####    
  w1coordinator:
    image: 192.168.10.123:5000/workbench1_coordinator:v1
    ports:
      - "8563:8563/udp"
    container_name: w1coordinator
    networks:
      gregor-chair-network:
        ipv4_address: 192.1.1.10 
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.gocas == w1 ]
      restart_policy:
        condition: on-failure 
      resources:
        limits:
          memory: 500M
    volumes:
      - /tmp:/tmp
    links:
      - w1controller
    privileged: true
  w1controller:
    image: 192.168.10.123:5000/workbench1controllerms:v1
    container_name: w1controller
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.gocas == w1 ]
      restart_policy:
        condition: on-failure 
      resources:
        limits:
          memory: 500M
    volumes:
      - /tmp:/tmp
      - /dev/gpiomem:/dev/gpiomem
    privileged: true
    environment:
      - PYTHONUNBUFFERED=1
### W2 SERVICES ####    
  w2coordinator:
    image: 192.168.10.123:5000/workbench2_coordinator:v1
    ports:
      - "8565:8565/udp"
    container_name: w2coordinator
    networks:
      gregor-chair-network:
        ipv4_address: 192.1.1.20 
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.gocas == w2 ]
      restart_policy:
        condition: on-failure 
      resources:
        limits:
          memory: 500M
    volumes:
      - /tmp:/tmp
      - /dev/gpiomem:/dev/gpiomem
    links:
      - w2controller
    privileged: true
  w2controller:
    image: 192.168.10.123:5000/workbench2controllerms:v1
    container_name: w2controller
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.gocas == w2 ]
      restart_policy:
        condition: on-failure 
      resources:
        limits:
          memory: 500M
    volumes:
      - /tmp:/tmp
      - /dev/gpiomem:/dev/gpiomem
    privileged: true
    environment:
      - PYTHONUNBUFFERED=1
### R1 SERVICES ####
  robot1controller:
    image: 192.168.10.123:5000/robot1controllerms:v1
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.gocas == r1 ]
      restart_policy:
        condition: on-failure 
      resources:
        limits:
          memory: 500M
    volumes:
      - /tmp:/tmp
      - /dev/gpiomem:/dev/gpiomem
    privileged: true
    environment:
      - PYTHONUNBUFFERED=1
  workertask1:
    image: 192.168.10.123:5000/workertask1:v1
    container_name: workertask1
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.gocas == r1 ]
      restart_policy:
        condition: on-failure 
      resources:
        limits:
          memory: 500M
    volumes:
      - /tmp:/tmp
    links:
      - robot1controller
    environment:
      - PYTHONUNBUFFERED=1
  workertask4:
    image: 192.168.10.123:5000/workertask4:v1
    container_name: workertask4
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.gocas == r1 ]
      restart_policy:
        condition: on-failure 
      resources:
        limits:
          memory: 500M
    volumes:
      - /tmp:/tmp
    links:
      - robot1controller
    environment:
      - PYTHONUNBUFFERED=1
  r1coordinator:
    image: 192.168.10.123:5000/robot1_coordinator:v1
    networks:
      gregor-chair-network:
        ipv4_address: 192.1.1.30 
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.gocas == r1 ]
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 500M
    volumes:
      - /tmp:/tmp
    links:
      - workertask1
      - workertask4
      - w1coordinator
      - w2coordinator
### R2 SERVICES ####
  robot2controller:
    image: 192.168.10.123:5000/robot2controllerms:v1
    container_name: robot2controller
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.gocas == r2 ]
      restart_policy:
        condition: on-failure 
      resources:
        limits:
          memory: 500M
    volumes:
      - /tmp:/tmp
      - /dev/gpiomem:/dev/gpiomem
    privileged: true
    environment:
      - PYTHONUNBUFFERED=1
  workertask2:
    image: 192.168.10.123:5000/workertask2:v1
    container_name: workertask2
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.gocas == r2 ]
      restart_policy:
        condition: on-failure 
      resources:
        limits:
          memory: 500M
    volumes:
      - /tmp:/tmp
    links:
      - robot2controller
    environment:
      - PYTHONUNBUFFERED=1
  workertask3:
    image: 192.168.10.123:5000/workertask3:v1
    container_name: workertask3
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.gocas == r2 ]
      restart_policy:
        condition: on-failure 
      resources:
        limits:
          memory: 500M
    volumes:
      - /tmp:/tmp
    links:
      - robot2controller
    environment:
      - PYTHONUNBUFFERED=1
  workertask5:
    image: 192.168.10.123:5000/workertask5:v1
    container_name: workertask5
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.gocas == r2 ]
      restart_policy:
        condition: on-failure 
      resources:
        limits:
          memory: 500M
    volumes:
      - /tmp:/tmp
    links:
      - robot2controller
    environment:
      - PYTHONUNBUFFERED=1
  r2coordinator:
    image: 192.168.10.123:5000/robot2_coordinator:v1
    networks:
      gregor-chair-network:
        ipv4_address: 192.1.1.40 
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.gocas == r2 ]
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 500M
    volumes:
      - /tmp:/tmp
    links:
      - workertask2
      - workertask3
      - workertask5
      - w1coordinator
      - w2coordinator
### R3 SERVICES ####
  robot3controller:
    image: 192.168.10.123:5000/robot3controllerms:v1
    container_name: robot3controller
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.gocas == r3 ]
      restart_policy:
        condition: on-failure 
      resources:
        limits:
          memory: 500M
    volumes:
      - /tmp:/tmp
      - /dev/gpiomem:/dev/gpiomem
    privileged: true
    environment:
      - PYTHONUNBUFFERED=1
  workertask6:
    image: 192.168.10.123:5000/workertask6:v1
    container_name: workertask6
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.gocas == r3 ]
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 500M 
    volumes:
      - /tmp:/tmp
    links:
      - robot3controller
    environment:
      - PYTHONUNBUFFERED=1
  workertask7:
    image: 192.168.10.123:5000/workertask7:v1
    container_name: workertask7
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.gocas == r3 ]
      restart_policy:
        condition: on-failure 
      resources:
        limits:
          memory: 500M
    volumes:
      - /tmp:/tmp
    links:
      - robot3controller
    environment:
      - PYTHONUNBUFFERED=1
  workertask8:
    image: 192.168.10.123:5000/workertask8:v1
    container_name: workertask8
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.gocas == r3 ]
      restart_policy:
        condition: on-failure 
      resources:
        limits:
          memory: 500M
    volumes:
      - /tmp:/tmp
    links:
      - robot3controller
    environment:
      - PYTHONUNBUFFERED=1
  r3coordinator:
    image: 192.168.10.123:5000/robot3_coordinator:v1
    networks:
      gregor-chair-network:
        ipv4_address: 192.1.1.50 
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.gocas == r3 ]
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 500M
    volumes:
      - /tmp:/tmp
    links:
      - workertask6
      - workertask7
      - workertask8
      - w1coordinator
      - w2coordinator


