#!/bin/bash

hosts=(
pi@192.168.10.123 #Robot1
pi@192.168.10.123 #Robot2
pi@192.168.10.123 #Robot3
pi@192.168.10.123 #Workbench2
)


exec_cmd() {
 sudo ufw allow from $3 to any port 2377
 echo "[$1] $2"
 echo ""
 #sudo usermod -aG docker $USER
 sshpass -p sseg ssh $1 $2
 echo ""
}

for host in "${hosts[@]}"
do
        ip=$(cut -d "@" -f 2 <<< "$host")
        echo $ip
	exec_cmd $host "$@" $ip
done

