version: "2"
networks:
  gregor-chair-network-w1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.4.0/24

services:
  node-exporter:
    image: prom/node-exporter:v0.18.1
    container_name: w1_node-exporter
    ports:
      - "9100:9100"
    restart: always
  cadvisor:
    image: budry/cadvisor-arm:latest #google/cadvisor:v0.33.0  #
    container_name: w1_cadvisor
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true
    depends_on:
      - w1coordinator
  w1_assembly_coordinator:
    build:
      context: ./Workbench1_Coordinator
      dockerfile: Dockerfile
    container_name: w1_assembly_coordinator
    ports:
      - "8563:8563/udp"
    networks:
      gregor-chair-network-w1:
        ipv4_address: 192.168.4.40
    volumes:
      - /tmp:/tmp
    links:
      - w1controller
    mem_limit: 500m
  w1_controller:
    build:
      context: ./Workbench1ControllerMs
      dockerfile: Dockerfile
    container_name: w1controller
    volumes:
      - /tmp:/tmp
      - /dev/gpiomem:/dev/gpiomem
    privileged: true
    environment:
      - PYTHONUNBUFFERED=1
    mem_limit: 500m


