version: "2"
networks:
  gregor-chair-network-w1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.4.0/24

services:

  w1coordinator:
    build:
      context: ./Workbench1_Coordinator
      dockerfile: Dockerfile
    container_name: w1coordinator
    ports:
      - "8563:8563/udp"
    networks:
      gregor-chair-network-w1:
        ipv4_address: 192.168.4.40
    volumes:
      - /tmp:/tmp
    links:
      - w1controller
    cpus: 0.7
    mem_limit: 500m
  w1controller:
    build:
      context: ./Workbench1ControllerMs
      dockerfile: Dockerfile
    container_name: w1controller
    volumes:
      - /tmp:/tmp
      - /dev/gpiomem:/dev/gpiomem
    privileged: true
    environment:
      - PYTHONUNBUFFERED=1
    cpus: 0.7
    mem_limit: 500m


