version: "2"
#version: '3.2'

services:
  grafana:
    image: grafana/grafana:6.3.5 #5.4.3
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./Grafana/login_config
    volumes:
      - ./Grafana/grafana_db:/var/lib/grafana:rw #needs command 'sudo chmod -R 777 Grafana/grafana_db'
      - ./Grafana/provisioning/datasource:/etc/grafana/provisioning/datasources
      - ./Grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus:v2.12.0
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./Prometheus/prometheus_db:/prometheus/data:rw #needs command 'sudo chmod -R 777 Prometheus/prometheus_db'

