# my global config
global:
  scrape_interval:     10s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 10s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  external_labels:
    monitor:  'GOCAS'

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
  # - 'prometheus.yml'
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

##############
# Prometheus #  
##############
  - job_name: 'prometheus'
    scrape_interval: 10s
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['localhost:9090'] 

###############
# Robot1 Node #  
###############
  - job_name: 'robot1'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.10.123:8080','192.168.10.123:9100']
        labels:
          group:  'robot1'
          instance: 'robot1'

###############
# Robot2 Node #  
###############
  - job_name: 'robot2'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.10.124:8080','192.168.10.124:9100']
        labels:
          group:  'robot2'
          instance: 'robot2'

###############
# Robot3 Node #  
###############
  - job_name: 'robot3'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.10.121:8080','192.168.10.121:9100']
        labels:
          group:  'robot3'
          instance: 'robot3'

###################
# Workbench1 Node #  
###################
  - job_name: 'workbench1'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.10.122:8080','192.168.10.122:9100']
        labels:
          group:  'workbench1'
          instance: 'workbench1'

###################
# Workbench2 Node #  
###################
  - job_name: 'workbench2'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.10.125:8080','192.168.10.125:9100']
        labels:
          group:  'workbench2'
          instance: 'workbench2'
