FROM frolvlad/alpine-python3:latest
#FROM arm32v6/python:3.5-alpine
COPY . /Workbench1ControllerMs
WORKDIR /Workbench1ControllerMs
# RUN pip install -r requirements.txt
# ENTRYPOINT ["python3","-u","-m","PickAndPlace.pickAndPlace"]
ENTRYPOINT ["python3","main.py"]

