version: "2"

networks:
  gregor-chair-network-r3:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24
          gateway: 172.16.239.11
volumes:
  Robot3socket:
    driver: "local"
  Workertask3socket:
    driver: "local"
services:
  robot3:
    build: 
      context: ./Robot3_CPMS
      dockerfile: Dockerfile
    networks:
      gregor-chair-network-r3:
        ipv4_address: 172.16.239.50
    volumes:
      - Robot3socket:/tmp
    mem_limit: 700m
  workertask1:
    build:
      context: ./Worker_Task3
      dockerfile: Dockerfile
    volumes:
      - Workertask3socket:/tmp
    links:
      - robot2
    volumes_from:
      - robot2
    mem_limit: 700m
  pickandplace:
    build:
      context: ./PickAndPlace
      dockerfile: Dockerfile
    links:
      - workertask3
    volumes_from:
      - workertask3
#    cpus: 0.6
    mem_limit: 700m
  pickandinsert:
    build:
      context: ./PickAndInsert
      dockerfile: Dockerfile
    links:
      - workertask3
    volumes_from:
      - workertask3
#    cpus: 0.6
    mem_limit: 700m

