version: "2.2"

networks:
  gregor-chair-network-r1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.240.0/24
          gateway: 172.16.240.11
volumes:
  Robot1socket:
    driver: "local"
  Workertask1socket:
    driver: "local"
  Workertask2socket:
    driver: "local"
  RobotControllersocket:
    driver: "local"
services:
  robot1:
    build:
      context: ./Robot1_Coordinator
      dockerfile: Dockerfile
    networks:
      gregor-chair-network-r1:
        ipv4_address: 172.16.240.30
    volumes:
      - Robot1socket:/tmp
    mem_limit: 700m
  workertask1:
    build:
      context: ./Worker_Task1
      dockerfile: Dockerfile
    volumes:
      - Workertask1socket:/tmp
    links:
      - robot1
    volumes_from:
      - robot1
    mem_limit: 700m
  workertask2:
    build:
      context: ./Worker_Task2
      dockerfile: Dockerfile
    volumes:
      - Workertask2socket:/tmp
    links:
      - robot1
    volumes_from:
      - robot1
    mem_limit: 700m
  robotcontroller:
    build:
      context: ./RobotControllerMs
      dockerfile: Dockerfile
    volumes:
      - RobotControllersocket:/tmp
    links:
      - robot1
    volumes_from:
      - robot1
    mem_limit: 700m

