version: "2"
#version: '3.2'
networks:
  gregor-chair-network-r1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24

services:
  node-exporter:
    image: prom/node-exporter:v0.18.1
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: always
  cadvisor:
    image: budry/cadvisor-arm:latest  #google/cadvisor:v0.33.0
    container_name: cadvisor
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true
    depends_on:
      - robot1coordinator
  robot1coordinator:
    build:
      context: ./Robot1_Coordinator
      dockerfile: Dockerfile
    container_name: r1coordinator
    networks:
      gregor-chair-network-r1:
        ipv4_address: 192.168.1.10
    volumes:
      - /tmp:/tmp
    links:
      - workertask1
      - workertask4
#    cpus: 0.6
#    mem_limit: 400m
  workertask1:
    build:
      context: ./WorkerTask1
      dockerfile: Dockerfile
    container_name: workertask1
    volumes:
      - /tmp:/tmp
    links:
      - robot1controller
    environment:
      - PYTHONUNBUFFERED=1
#    cpus: 0.6
#    mem_limit: 400m
  workertask4:
    build:
      context: ./WorkerTask4
      dockerfile: Dockerfile
    container_name: workertask4
    volumes:
      - /tmp:/tmp
    links:
      - robot1controller
    environment:
      - PYTHONUNBUFFERED=1
#    cpus: 0.6
#    mem_limit: 400m
  robot1controller:
    build:
      context: ./RobotControllerMs
      dockerfile: Dockerfile
    container_name: robot1controller
    volumes:
      - /tmp:/tmp
      - /dev/gpiomem:/dev/gpiomem
    privileged: true
    environment:
      - PYTHONUNBUFFERED=1
#    cpus: 0.6
#    mem_limit: 400m
