FROM frolvlad/alpine-python3:latest
COPY . /RobotControllerMs
WORKDIR /RobotControllerMs
# RUN pip install -r requirements.txt
# ENTRYPOINT ["python3","-u","-m","PickAndPlace.pickAndPlace"]
ENTRYPOINT ["python3","main.py"]

