{
 "title": "Host Statistics",
 "description": "Basic host stats: CPU, Memory Usage, Disk Utilisation,  Filesystem usage, Temperature",
 "time": { "from": "now-2m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Machine",
    "query": "up{job=\"node-exporter\"}"
   },
   { "name": "job", "label": "job", "query": "node-exporter" }
  ]
 },
 "panels": [
  {
   "title": "System Uptime",
   "type": "singlestat",
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "System CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "machine_cpu_cores" }
   ]
  },
  {
   "title": "Free Storage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{device='/dev/root',fstype='ext4',group='node-exporter',instance='$instance',job='node-exporter',mountpoint='/etc/hosts'}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"$job\",instance=\"$instance\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job='$job',instance='$instance'} - node_memory_MemFree_bytes{job='node-exporter',instance='$instance'} - node_memory_Buffers_bytes{job='node-exporter',instance='$instance'} - node_memory_Cached_bytes{job='node-exporter',instance='$instance'}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job='$job',instance='$instance'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job='$job',instance='$instance'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job='$job',instance='$instance'}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{job='$job',instance='$instance'}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"$job\",instance=\"$instance\"}[5m])",
     "legendFormat": "{{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"$job\",instance=\"$instance\"}[5m])",
     "legendFormat": "{{device}} transmit"
    }
   ]
  },
  {
   "title": "Filesystem Fullness",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (node_filesystem_free_bytes{job='$job',instance='$instance',fstype!='rootfs',mountpoint!~'/(run|var).*',mountpoint!=''} / node_filesystem_size_bytes{job='$job',instance='$instance'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk I/O Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{job='$job',instance='$instance',device!~'^(md\\\\d+$|dm-)'}[5m]) / 1000",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}