version: "2"

networks:
  gregor-chair-network-w1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24
          gateway: 172.16.239.11
services:
  w1:
    build: 
      context: ./Workbench1_CPMS
      dockerfile: Dockerfile
    ports:
      - "8563:8563/udp"
    networks:
      gregor-chair-network:
        ipv4_address: 172.16.239.10 
