version: "2"
#version: '3.2'
networks:
  gregor-chair-network-w2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.5.0/24

volumes:
  W2CoordinatorSocket:
    driver: "local"
services:
  w2coordinator:
    build:
      context: ./Workbench2_Coordinator
      dockerfile: Dockerfile
    container_name: w2coordinator
    ports:
      - "8565:8565/udp"
    networks:
      gregor-chair-network-w2:
        ipv4_address: 192.168.5.50
    volumes:
      - /tmp:/tmp
    links:
      - w2controller
    cpus: 0.7
    mem_limit: 500m
  w2controller:
    build:
      context: ./Workbench2ControllerMs
      dockerfile: Dockerfile
    container_name: w2controller
    volumes:
      - /tmp:/tmp
      - /dev/gpiomem:/dev/gpiomem
    privileged: true
    environment:
      - PYTHONUNBUFFERED=1
    cpus: 0.7
    mem_limit: 500m



