version: "2"
#version: '3.2'
networks:
  gregor-chair-network-r3:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.3.0/24
#        - gateway: 172.16.240.11

volumes:
  Robot3CoordinatorSocket:
    driver: "local"
  Robot2ControllerSocket:
    driver: "local"
  Workertask6Socket:
    driver: "local"
  Workertask7Socket:
    driver: "local"
  Workertask8Socket:
    driver: "local"
services:
#  grafana:
#    image: grafana/grafana:latest
#    container_name: grafana
#    restart: always
#    ports:
#      - "3000:3000"
#    environment:
#      - GF_INSTALL_PLUGINS=grafana-piechart-panel,jdbranham-diagram-panel
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=gocas
#    depends_on:
#      - prometheus
#  prometheus:
#    image: prom/prometheus:latest
#    container_name: prometheus
#    restart: always
#    ports:
#      - 9090:9090
#    command:
#      - --config.file=/etc/prometheus/prometheus.yml
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
#      - ./prometheusdb:/prometheus/data:rw  #needs command 'sudo chmod -R 777 prometheusdb'
#    depends_on:
#      - cadvisor
#      - node-exporter
#  node-exporter:
#    image: prom/node-exporter:latest
#    container_name: node-exporter
#    ports:
#      - "9100:9100"
#    restart: always
#  cadvisor:
#    image: google/cadvisor:latest
#    container_name: cadvisor
#    restart: always
#    ports:
#      - "8080:8080"
#    volumes:
#      - /:/rootfs:ro
#      - /var/run:/var/run:rw
#      - /sys:/sys:ro
#      - /var/lib/docker/:/var/lib/docker:ro
#    depends_on:
#      - w1
#      - robot1coordinator
#      - workertask1
#      - workertask2
#      - robot1controller
#    privileged: true
  robot3coordinator:
    build:
      context: ./Robot3_Coordinator
      dockerfile: Dockerfile
    container_name: r3coordinator
    networks:
      gregor-chair-network-r3:
        ipv4_address: 192.168.3.30
    volumes:
      - /tmp:/tmp
    links:
      - workertask6
      - workertask7
      - workertask8
  workertask6:
    build:
      context: ./Worker_Task6
      dockerfile: Dockerfile
    container_name: workertask6
    volumes:
      - /tmp:/tmp
    links:
      - robot3controller
    environment:
      - PYTHONUNBUFFERED=1
  workertask7:
    build:
      context: ./Worker_Task7
      dockerfile: Dockerfile
    container_name: workertask7
    volumes:
      - /tmp:/tmp
    links:
      - robot3controller
    environment:
      - PYTHONUNBUFFERED=1
#    cpus: 0.6
#    mem_limit: 700m
  workertask8:
    build:
      context: ./Worker_Task8
      dockerfile: Dockerfile
    container_name: workertask8
    volumes:
      - /tmp:/tmp
    links:
      - robot3controller
    environment:
      - PYTHONUNBUFFERED=1
#    cpus: 0.6
#    mem_limit: 700m
  robot3controller:
    build:
      context: ./RobotControllerMs
      dockerfile: Dockerfile
    container_name: robot3controller
    volumes:
      - /tmp:/tmp
      - /dev/gpiomem:/dev/gpiomem
    privileged: true
    environment:
      - PYTHONUNBUFFERED=1


