version: "2"

networks:
  gregor-chair-network-r3:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.3.0/24

services:
  node-exporter:
    image: prom/node-exporter:v0.18.1
    container_name: r3_node-exporter
    ports:
      - "9100:9100"
    restart: always
  cadvisor:
    image: budry/cadvisor-arm:latest #google/cadvisor:v0.33.0  #
    container_name: r3_cadvisor
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true
    depends_on:
      - r3_assembly_coordinator
  r3_assembly_coordinator:
    build:
      context: ./Robot3_Coordinator
      dockerfile: Dockerfile
    container_name: r3_assembly_coordinator
    networks:
      gregor-chair-network-r3:
        ipv4_address: 192.168.3.30
    volumes:
      - /tmp:/tmp
    links:
      - workertask6
      - workertask7
      - workertask8
    mem_limit: 500m
  workertask6:
    build:
      context: ./Worker_Task6
      dockerfile: Dockerfile
    container_name: workertask6
    volumes:
      - /tmp:/tmp
    links:
      - r3_controller
    environment:
      - PYTHONUNBUFFERED=1
    mem_limit: 500m
  workertask7:
    build:
      context: ./Worker_Task7
      dockerfile: Dockerfile
    container_name: workertask7
    volumes:
      - /tmp:/tmp
    links:
      - r3_controller
    environment:
      - PYTHONUNBUFFERED=1
    mem_limit: 500m
  workertask8:
    build:
      context: ./Worker_Task8
      dockerfile: Dockerfile
    container_name: workertask8
    volumes:
      - /tmp:/tmp
    links:
      - r3_controller
    environment:
      - PYTHONUNBUFFERED=1
    mem_limit: 500m
  r3_controller:
    build:
      context: ./RobotControllerMs
      dockerfile: Dockerfile
    container_name: robot3controller
    volumes:
      - /tmp:/tmp
      - /dev/gpiomem:/dev/gpiomem
    privileged: true
    environment:
      - PYTHONUNBUFFERED=1
    mem_limit: 500m

