version: "2"

networks:
  gregor-chair-network-r3:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.3.0/24

services:
  robot3coordinator:
    build:
      context: ./Robot3_Coordinator
      dockerfile: Dockerfile
    container_name: r3coordinator
    networks:
      gregor-chair-network-r3:
        ipv4_address: 192.168.3.30
    volumes:
      - /tmp:/tmp
    links:
      - workertask6
      - workertask7
      - workertask8
    cpus: 0.7
    mem_limit: 500m
  workertask6:
    build:
      context: ./Worker_Task6
      dockerfile: Dockerfile
    container_name: workertask6
    volumes:
      - /tmp:/tmp
    links:
      - robot3controller
    environment:
      - PYTHONUNBUFFERED=1
    cpus: 0.7
    mem_limit: 500m
  workertask7:
    build:
      context: ./Worker_Task7
      dockerfile: Dockerfile
    container_name: workertask7
    volumes:
      - /tmp:/tmp
    links:
      - robot3controller
    environment:
      - PYTHONUNBUFFERED=1
    cpus: 0.7
    mem_limit: 500m
  workertask8:
    build:
      context: ./Worker_Task8
      dockerfile: Dockerfile
    container_name: workertask8
    volumes:
      - /tmp:/tmp
    links:
      - robot3controller
    environment:
      - PYTHONUNBUFFERED=1
    cpus: 0.7
    mem_limit: 500m
  robot3controller:
    build:
      context: ./RobotControllerMs
      dockerfile: Dockerfile
    container_name: robot3controller
    volumes:
      - /tmp:/tmp
      - /dev/gpiomem:/dev/gpiomem
    privileged: true
    environment:
      - PYTHONUNBUFFERED=1


